### PR TITLE
Fix SleepMode Bug

### PR DESCRIPTION
**Pull request by tobid7**
I just created a lpp-3ds version, that fixes the SleepMode Bug.

I've updated the Code and the Binarys.
I don't know if you want to create a Release with a new `.cia` file. 
I could create one for a release.

### CODE REVIEW

**Comment by Creckeryop** [comment]
Wow, nice work, you've fixed lpp-3ds, that's really cool. I really now doesn't have any tools to compile this code to cia, can you help me with that? :D Also I really dunno if your lpp-3ds fork supports long numbers? If that so, maybe we can delete the end screen?

**Comment by tobid7** [comment]
I think it's a good idea to create a 3dsx too because since idk its poaaible to use romfs in 3dsx files.
I just extract your 1.0 cia or so to get the banner and icn and then i create the two files `.cia, .3dsx` later this day.

I'll see if you can do that with the long numbers.

But first I need to update my fork from dkaR45 and 2016 libraries to dkaR56 qnd newest libraries xd.
I think using a newer lua version supports larger numbers:)

**Comment by Creckeryop** [comment]
I do have banner.bin and icon.bin file i think

**Comment by Creckeryop** [comment]
https://drive.google.com/file/d/1CPQ_3qbgyj2SQefpK-rc88yu33ot5gcp/view?usp=sharing

**Comment by tobid7** [comment]
Here are the 3dsx and Cia:
https://drive.google.com/file/d/1-Xm-_8q7DqusgLPoOqFbsa9eL381hTx_/view?usp=sharing
And My buildscripts:
https://drive.google.com/drive/folders/1di0Vlr_iUqzRa04Rt1WmcfVAEMDQ53NQ?usp=sharing
Only the build.sh is functional if you have makerom:)

I could change the logo.bin and some thiing but I had not the Time to do that yet:)

I will Test the Cia and you can upload both `3dsx, cia` if you want to create a release.

**Comment by Creckeryop** [comment]
It's okay, don't hurry

**Comment by Creckeryop** [comment]
Thank you for doing that :)

**Pull request merged**
